### ISSUE TITLE
Migrate website repo https://git.eclipse.org/c/www.eclipse.org/equinox.git/ to github

### ISSUE THREAD

**Issue by merks** [eclipse-equinox/.github#1]
This repo serves the content of the project site https://www.eclipse.org/equinox/

This is similar to the following issue:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/168

**Comment by bjhargrave** [comment]
`.github` (this repo) is not the proper repo to host a website. As far as I know, EF desires to host all websites in their GitLab instance. See <https://gitlab.eclipse.org/eclipsefdn/it/websites>.

**Comment by merks** [comment]
Note though that the foundation happily migrated these:

https://github.com/eclipse-platform/www.eclipse.org-eclipse-news
https://github.com/eclipse-platform/www.eclipse.org-eclipse

I'll ask the powers that be if that was done in error...

**Comment by vogella** [comment]
We just need a way to publish via a build job to the foundation website.

**Comment by bjhargrave** [comment]
> Note though that the foundation happily migrated these:

Sure, but they are in repos which are not their github organization's `.github` repo. The `.github` repo is a special organization repo. I am just questioning why this issue is in this repo.

**Comment by merks** [comment]
Given there is no documentation of where to open an issue and given the website github repo doesn't exist such that I cannot open the issue there, I opened it here.  

Other Eclipse projects saying this this:

```
The Eclipse PDE project is split into multiple Git repositories, which are all part of this organization. If you face an issue and have a sense of which particular GitHub repository is most related, you can open your issue against that repository. If you're unsure, you can open an issue against this current repositories and the issue will then be moved as best by maintainers.
```

I.e., the following do that so I made the bold assumption that this applies for Equinox as well:

https://github.com/eclipse-platform/
https://github.com/eclipse-pde/

Sorry if that's a bad assumption.

**Comment by vogella** [comment]
@merks hopefully we will reduce this confusion in the future by reducing the number of Github repos.

**Comment by chrisguindon** [comment]
> .github (this repo) is not the proper repo to host a website. As far as I know, EF desires to host all websites in their GitLab instance. See https://gitlab.eclipse.org/eclipsefdn/it/websites.

Hi @bjhargrave,

The sites listed under https://gitlab.eclipse.org/eclipsefdn/it/websites. are mostly websites that the EF webdev team maintains. I think you are referring to our recent migration of osgi.org: https://gitlab.eclipse.org/eclipsefdn/it/websites/osgi.org/-/issues/41

However, we don't have any plan on migrating Project websites there! 


With this said, we are also working on deprecating Gerrit. There is a wiki page about that move here:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/wikis/Gerrit/Gerrit-and-Bugzilla-deprecation-and-migration-plan

**Comment by akurtakov** [comment]
Webmaster did the migration and new page is hosted at https://github.com/eclipse-equinox/equinox-website
